[settings]
idiomatic_version_file_enable_tools = ["node", "python", "go", "terraform", "rust"]

[tools]
node = "lts"
go = "latest"
bun = "latest"
gcloud = "latest"
terraform = "latest"
biome = "latest"
oxfmt = "latest"
rust = "latest"
rust-analyzer = "latest"
ty = "latest"
ruff = "latest"
