-- Servers come from brew (Brewfile) / mise (.mise.toml) and launch off $PATH -- no mason.
-- Own group, separate from config/autocmds.lua (see the note there).
local augroup = vim.api.nvim_create_augroup('user_lsp', { clear = true })

-- virtual_text is off by default, so show the message on jump instead. This hooks
-- Neovim's own [d / ]d maps; do not re-map those keys here.
vim.diagnostic.config({
  jump = {
    on_jump = function(_, bufnr)
      vim.diagnostic.open_float({ bufnr = bufnr, scope = 'cursor' })
    end,
  },
})

vim.lsp.config('*', {
  capabilities = require('blink.cmp').get_lsp_capabilities({}, false),
})

vim.lsp.config('yamlls', {
  cmd = { 'yaml-language-server', '--stdio' },
  filetypes = { 'yaml' },
  root_markers = { '.git' },
  settings = {
    yaml = {
      schemas = {
        kubernetes = {
          'base/**/*.yaml',
          'overlays/**/*.yaml',
          'clusters/**/*.yaml',
        },
      },
      validate = true,
      completion = true,
      hover = true,
    },
  },
})

-- rust-analyzer -> mise | typescript-language-server -> brew
vim.lsp.config('rust_analyzer', {
  cmd = { 'rust-analyzer' },
  filetypes = { 'rust' },
  root_markers = { 'Cargo.toml', 'Cargo.lock', '.git' },
})
vim.lsp.config('ts_ls', {
  cmd = { 'typescript-language-server', '--stdio' },
  filetypes = {
    'javascript', 'javascriptreact', 'javascript.jsx',
    'typescript', 'typescriptreact', 'typescript.tsx',
  },
  root_markers = { 'tsconfig.json', 'jsconfig.json', 'package.json', '.git' },
})
vim.lsp.config('ty', {
  cmd = { 'ty', 'server' },
  filetypes = { 'python' },
  root_markers = { 'ty.toml', 'pyproject.toml', 'setup.py', '.git' },
})

-- Formatters need root_dir, not root_markers: on a miss root_markers still attaches
-- the client in single-file mode, and format-on-save would then rewrite the buffer
-- with that formatter's defaults. Not calling on_dir skips the attach instead.
local function root_or_skip(markers)
  return function(bufnr, on_dir)
    local root = vim.fs.root(bufnr, markers)
    if root then
      on_dir(root)
    end
  end
end

-- biome -> mise
vim.lsp.config('biome', {
  cmd = { 'biome', 'lsp-proxy' },
  -- json is left out on purpose: .config/karabiner/karabiner.json is generated by
  -- Karabiner and sits next to a biome.json, so saving it here would rewrite it.
  filetypes = {
    'javascript', 'javascriptreact',
    'typescript', 'typescriptreact',
  },
  root_dir = root_or_skip({ 'biome.json', 'biome.jsonc' }),
})

-- oxfmt -> mise. Formatting only; oxlint has its own server and is not wired up here.
vim.lsp.config('oxfmt', {
  cmd = { 'oxfmt', '--lsp' },
  filetypes = {
    'javascript', 'javascriptreact',
    'typescript', 'typescriptreact',
  },
  root_dir = root_or_skip({ '.oxfmtrc.json', '.oxfmtrc.jsonc' }),
})

-- gofumpt / staticcheck are built into gopls; there are no separate binaries.
vim.lsp.config('gopls', {
  cmd = { 'gopls' },
  filetypes = { 'go', 'gomod', 'gowork', 'gotmpl' },
  root_markers = { 'go.work', 'go.mod', '.git' },
  settings = {
    gopls = {
      gofumpt = true,
      staticcheck = true,
      analyses = { unusedparams = true, shadow = true },
    },
  },
})

vim.lsp.enable({ 'yamlls', 'rust_analyzer', 'ts_ls', 'ty', 'gopls', 'biome', 'oxfmt' })

vim.api.nvim_create_autocmd('BufWritePre', {
  group = augroup,
  callback = function(args)
    local gopls = vim.lsp.get_clients({ bufnr = args.buf, name = 'gopls' })[1]
    if gopls then
      local params = vim.lsp.util.make_range_params(0, gopls.offset_encoding)
      params.context = { only = { 'source.organizeImports' }, diagnostics = {} }
      -- 1000ms is not enough for the first save of a session: gopls loads the package first.
      local responses = vim.lsp.buf_request_sync(args.buf, 'textDocument/codeAction', params, 3000)
      for _, response in pairs(responses or {}) do
        for _, action in pairs(response.result or {}) do
          if action.edit then
            vim.lsp.util.apply_workspace_edit(action.edit, gopls.offset_encoding)
          end
        end
      end
    end
    vim.lsp.buf.format({
      bufnr = args.buf,
      async = false,
      timeout_ms = 3000,
      -- ts_ls formats to its own style, which matches no project's config. Leave
      -- js/ts formatting to biome / oxfmt, which attach only inside their own
      -- projects -- a project with neither is left untouched on save.
      filter = function(client)
        return client.name ~= 'ts_ls'
      end,
    })
  end,
})

vim.api.nvim_create_autocmd('LspAttach', {
  group = augroup,
  callback = function(args)
    local buf = args.buf
    local function lmap(lhs, rhs, desc)
      vim.keymap.set('n', lhs, rhs, { buffer = buf, desc = 'LSP: ' .. desc })
    end
    lmap('K', vim.lsp.buf.hover, 'Hover docs')
    lmap('gd', function() Snacks.picker.lsp_definitions() end, 'Go to definition')
    lmap('grr', function() Snacks.picker.lsp_references() end, 'References')
    lmap('gri', function() Snacks.picker.lsp_implementations() end, 'Implementations')
    lmap('grt', function() Snacks.picker.lsp_type_definitions() end, 'Type definitions')
    lmap('gO', function() Snacks.picker.lsp_symbols() end, 'Document symbols')
    lmap('<leader>rn', vim.lsp.buf.rename, 'Rename symbol')
    lmap('<leader>ca', vim.lsp.buf.code_action, 'Code action')
    lmap('<leader>d', vim.diagnostic.open_float, 'Show diagnostic under cursor')
    lmap('<leader>ih', function()
      vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = buf }), { bufnr = buf })
    end, 'Toggle inlay hints')
  end,
})
