# ~/.config/starship.toml

# プロンプトの表示順序を制御
format = """$directory$git_branch$git_status$kubernetes$gcloud$all"""

[aws]
disabled = true

[gcloud]
format = '[$active]($style) '

[terraform]
disabled = true

[kubernetes]
format = '[$context]($style) '
style = "bright-yellow"
disabled = false

[[kubernetes.contexts]]
context_pattern = "prd-.*"
style = "bold red"

[[kubernetes.contexts]]
context_pattern = "stg-.*"
style = "yellow"

[[kubernetes.contexts]]
context_pattern = "dev.*"
style = "green"

[[kubernetes.contexts]]
context_pattern = "kind-.*"
style = "dimmed green"

[[kubernetes.contexts]]
context_pattern = "pi"
style = "dimmed green"
