[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "never"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideNamedConstructor = true

[language-server.rust-analyzer.config.files]
watcher = "server"
