name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        # Create test directories
        mkdir -p ~/.config/zsh
        mkdir -p ~/.config/karabiner/assets/complex_modifications
        mkdir -p ~/.config/ghostty
        
        # Backup existing files if they exist
        for file in ~/.zshrc ~/.vimrc; do
          if [ -f "$file" ]; then
            cp "$file" "${file}.github-backup"
          fi
        done
    
    - name: Test install.sh (dry run simulation)
      run: |
        set -e  # Exit on any error
        
        echo "Starting install.sh validation..."
        
        # Check if script is executable
        if test -x ./install.sh; then
          echo "✓ install.sh is executable"
        else
          echo "✗ install.sh is not executable"
          exit 1
        fi
        
        # Validate script syntax
        if bash -n ./install.sh; then
          echo "✓ install.sh syntax is valid"
        else
          echo "✗ install.sh has syntax errors"
          exit 1
        fi
        
        # Check if Homebrew would be installed (without actually installing)
        if ! command -v brew &> /dev/null; then
          echo "✓ Homebrew installation would be triggered"
        else
          echo "✓ Homebrew already available"
        fi
        
        # Verify Brewfile exists in repository
        if test -f ./Brewfile; then
          echo "✓ Brewfile found in repository"
        else
          echo "✗ Brewfile not found"
          exit 1
        fi
        
        # Check for potential issues in install.sh
        echo "Checking for potential issues in install.sh:"
        
        # Check if script changes directory and references relative paths  
        if grep -q "cd \$HOME" ./install.sh && grep -q "\./Brewfile" ./install.sh; then
          echo "⚠️  Warning: Script changes to HOME directory but references ./Brewfile"
          echo "   This may cause 'file not found' errors"
        else
          echo "✓ No relative path issues detected"
        fi
        
        # Check if 'z' command is used (zoxide dependency)
        if grep -q "^z " ./install.sh; then
          echo "⚠️  Warning: Script uses 'z' command which requires zoxide to be installed first"
        else
          echo "✓ No zoxide dependency issues detected"
        fi
        
        # Check if Google Cloud CLI installation logic is present
        if grep -q "google-cloud-cli" ./install.sh; then
          echo "✓ Google Cloud CLI installation logic present"
        else
          echo "ℹ️  Google Cloud CLI installation logic not found (this is okay)"
        fi
        
        echo "✓ install.sh validation completed successfully"
    
    - name: Test link.sh
      run: |
        # Check if script is executable
        test -x ./link.sh
        
        # Validate script syntax
        bash -n ./link.sh
        
        # Test symbolic link creation (in safe mode)
        export DRY_RUN=true
        ./link.sh || true
        
        # Verify all source files exist
        while IFS=':' read -r source target; do
          if [ -f "$source" ]; then
            echo "✓ Source file exists: $source"
          else
            echo "✗ Missing source file: $source"
            exit 1
          fi
        done <<< "$(grep -E '^\s*"[^"]+:[^"]+"\s*$' link.sh | sed 's/[" ]//g')"
    
    - name: Test configuration files
      run: |
        # Check shell configurations
        test -f .zshrc
        test -f .config/zsh/alias.sh
        test -f .config/zsh/command.sh
        echo "✓ Shell configuration files exist"
        
        # Check vim configuration
        test -f .vimrc
        echo "✓ Vim configuration exists"
        
        # Check Karabiner configuration
        test -f .config/karabiner/assets/complex_modifications/personal_hagaspa.json
        echo "✓ Karabiner configuration exists"
        
        # Check Ghostty configuration
        test -f .config/ghostty/config
        echo "✓ Ghostty configuration exists"
        
        # Validate JSON files
        python3 -m json.tool .config/karabiner/assets/complex_modifications/personal_hagaspa.json > /dev/null
        echo "✓ Karabiner JSON is valid"
    
    - name: Test Brewfile
      run: |
        set -e
        
        echo "Testing Brewfile validity..."
        
        # Check if Brewfile exists
        if test -f ./Brewfile; then
          echo "✓ Brewfile found"
        else
          echo "✗ Brewfile not found"
          exit 1
        fi
        
        # Validate Brewfile syntax by parsing it
        echo "Checking Brewfile syntax..."
        if grep -E '^(tap|brew|cask|mas)' ./Brewfile > /dev/null; then
          echo "✓ Brewfile contains valid entries"
        else
          echo "✗ Brewfile appears to be empty or invalid"
          exit 1
        fi
        
        # Check for essential tools in Brewfile
        echo "Checking for essential tools..."
        essential_tools=("fzf" "gh" "zoxide")
        for tool in "${essential_tools[@]}"; do
          if grep -q "brew \"$tool\"" ./Brewfile; then
            echo "✓ Found essential tool: $tool"
          else
            echo "⚠️  Essential tool not found in Brewfile: $tool"
          fi
        done
        
        # If brew is available, test bundle validation (but don't fail on missing packages)
        if command -v brew &> /dev/null; then
          echo "Homebrew is available, testing bundle check..."
          if brew bundle check --file=./Brewfile; then
            echo "✓ All Brewfile dependencies are satisfied"
          else
            echo "ℹ️  Some packages not installed (expected in CI environment)"
            echo "   This is normal - CI doesn't pre-install all development tools"
          fi
        else
          echo "ℹ️  Homebrew not available in this environment"
        fi
        
        echo "✓ Brewfile validation completed"
    
    - name: Cleanup
      if: always()
      run: |
        # Restore backed up files
        for file in ~/.zshrc ~/.vimrc; do
          if [ -f "${file}.github-backup" ]; then
            mv "${file}.github-backup" "$file"
          fi
        done
        
        # Remove any test symlinks that might have been created
        for link in ~/.zshrc ~/.vimrc ~/.config/zsh/alias.sh ~/.config/zsh/command.sh; do
          if [ -L "$link" ]; then
            rm "$link"
          fi
        done