name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: ./.github/scripts/setup-environment.sh
    
    - name: Test install.sh (actual execution)
      run: ./.github/scripts/test-install.sh
    
    - name: Test link.sh
      run: ./.github/scripts/test-link.sh
    
    - name: Test configuration files
      run: ./.github/scripts/test-config.sh
    
    - name: Test Brewfile
      run: ./.github/scripts/test-brewfile.sh
    
    - name: Cleanup
      if: always()
      run: ./.github/scripts/cleanup-environment.sh